@id = 4420b321-ed21-4134-998b-6bd5e1372d97

PUT http://localhost:5094/breakfasts/{{id}}
Content-Type: application/json

{
    "name": "Vegan Sunshine 2",
    "description": "Vegan everything! Join us for a healthy breakfast..",
    "startDateTime": "2022-04-08T08:00:00",
    "endDateTime": "2022-04-08T11:00:00",
    "savory": [
        "Oatmeal",
        "Avocado Toast",
        "Omelette",
        "Salad"
    ],
    "Sweet": [
        "Cookie"
    ]
}